language: ruby
rvm:
- 2.1

before_script:
- chmod +x cibuild.sh

script:
  - bundle install
  - bundle exec travis-lint
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --check-favicon --verbose --check-html
  - ./cibuild.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
  - source

notifications:
  email: false