language: ruby
rvm:
- 2.1

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html

before_script:
- chmod +x cibuild.sh

script: "./cibuild.sh"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
  - source