name: Nandomoreira
description: " / Desenvolvimento Web e tudo mais.. "
meta_description: "Desenvolvedor Front-end/Wordpress, Design responsivo, HTML5, CSS3 e JavaScript."
keywords: "site, Curitiba, PR, Website, loja virtual, lojas virtuais, E-commerce, wordpress, frontend, front-end, html5, css3, javascript, jquery, seo, otimização, performance"

permalink   : :title
markdown    : kramdown
highlighter : pygments

logo: false

paginate: 6
paginate_path: "/page/:num"

baseurl: /
domain_name: 'nandomoreira.me'
google_analytics: 'UA-XXXXXXXX-X'

cover: '/assets/images/header-cover.jpg'

# Details for the RSS feed generator
url: 'nandomoreira.me'
author:
  name     : 'Fernando Moreira'
  image    : '/assets/images/author.jpg'
  email    : hi@nandomoreira.me
  url      : http://nandomoreira.me
  facebook : https://www.facebook.com/fernando.dev
  twitter  : https://twitter.com/nandomoreirame

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir : _sass
  style    : :compressed


compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]